# Generated by Django 4.2.2 on 2023-10-02 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(default='class-1.jpg', upload_to='class')),
                ('video', models.FileField(blank=True, null=True, upload_to='class')),
                ('level', models.CharField(choices=[('Pre-School', 'Pre-School'), ('Primary', 'Primary'), ('Junior High', 'Junior High')], max_length=15)),
                ('name', models.CharField(max_length=15, unique=True)),
                ('min_age', models.IntegerField()),
                ('max_age', models.IntegerField()),
                ('tuition_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tuition_interval', models.CharField(choices=[('Day', 'Day'), ('Month', 'Month'), ('Term', 'Term'), ('Year', 'Year')], max_length=15)),
                ('total_seats', models.IntegerField()),
                ('start_time', models.CharField(max_length=15)),
                ('close_time', models.CharField(max_length=15)),
            ],
        ),
    ]
