# Generated by Django 4.2.2 on 2023-10-02 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='close_time',
            field=models.TimeField(max_length=15),
        ),
        migrations.AlterField(
            model_name='class',
            name='start_time',
            field=models.TimeField(max_length=15),
        ),
    ]
