# Generated by Django 4.2.2 on 2023-10-02 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_class_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='slug',
            field=models.SlugField(default='nursery'),
            preserve_default=False,
        ),
    ]
