# Generated by Django 4.2.2 on 2023-10-03 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_gamescategory_games'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transportation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('registered_number', models.CharField(max_length=10)),
                ('driver_name', models.CharField(max_length=10)),
                ('driver_contact', models.CharField(max_length=12)),
                ('image', models.ImageField(blank=True, null=True, upload_to='transport')),
            ],
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='gallery'),
        ),
        migrations.AlterField(
            model_name='games',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='games'),
        ),
        migrations.AlterField(
            model_name='gamescategory',
            name='category',
            field=models.CharField(choices=[('Football', 'Football'), ('Volley', 'Volley'), ('Tag', 'Tag')], max_length=50),
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=100)),
                ('pickup_time', models.TimeField()),
                ('drop_time', models.TimeField()),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.transportation')),
            ],
        ),
    ]
