# Generated by Django 4.2.2 on 2023-10-03 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_transportation_registered_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportation',
            name='driver_contact',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='transportation',
            name='driver_name',
            field=models.CharField(max_length=100),
        ),
    ]
