# Generated by Django 4.2.2 on 2023-10-03 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_transportation_driver_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurCareer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=255)),
                ('posted_date', models.DateTimeField(auto_now_add=True)),
                ('deadline', models.DateField()),
                ('job_description', models.CharField(max_length=255)),
                ('picture', models.ImageField(blank=True, default='career.png', null=True, upload_to='careers')),
                ('employer_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
