# Generated by Django 4.2.2 on 2023-11-23 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='level',
            field=models.CharField(choices=[('Pre-School', 'Pre-School'), ('Primary', 'Primary'), ('Junior High', 'Junior High')], default=1, max_length=15),
            preserve_default=False,
        ),
    ]
