# Generated by Django 4.2.2 on 2023-11-23 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_onlineapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('picture_1', models.ImageField(default='', upload_to='blog')),
                ('blockquote', models.CharField(blank=True, max_length=255, null=True)),
                ('picture_2', models.ImageField(blank=True, null=True, upload_to='blog')),
                ('picture_3', models.ImageField(blank=True, null=True, upload_to='blog')),
                ('detail_1', models.TextField(blank=True, null=True)),
                ('detail_2', models.TextField(blank=True, null=True)),
                ('topic_3', models.CharField(blank=True, max_length=255, null=True)),
                ('detail_3', models.TextField(blank=True, null=True)),
                ('topic_4', models.CharField(blank=True, max_length=255, null=True)),
                ('detail_4', models.TextField(blank=True, null=True)),
                ('detail_5', models.TextField(blank=True, null=True)),
                ('detail_6', models.TextField(blank=True, null=True)),
                ('banner', models.BooleanField(default=False)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('author', models.CharField(max_length=155)),
                ('author_pic', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='blog')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.articlescategories')),
            ],
        ),
    ]
