# Generated by Django 4.2.2 on 2023-12-18 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_announcements'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Announcements',
            new_name='Announcement',
        ),
    ]
