# Generated by Django 4.2.2 on 2023-12-18 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_rename_activity_announcement_event_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='event',
            field=models.TextField(),
        ),
    ]
