# Generated by Django 4.2.2 on 2023-12-18 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_announcement_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherFees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission', models.IntegerField()),
                ('canteen', models.IntegerField()),
                ('uniform', models.IntegerField()),
                ('others', models.IntegerField()),
                ('class_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.class')),
            ],
        ),
    ]
