# Generated by Django 4.2.2 on 2023-12-18 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_rename_otherfees_otherfee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otherfee',
            name='class_level',
        ),
        migrations.AddField(
            model_name='otherfee',
            name='level',
            field=models.CharField(choices=[('Pre-School', 'Pre-School'), ('Primary', 'Primary'), ('Junior High', 'Junior High')], default=1, max_length=15),
            preserve_default=False,
        ),
    ]
