# Generated by Django 4.2.2 on 2023-12-19 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_alter_assignment_created_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmitAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_id', models.CharField(max_length=125)),
                ('answer_file', models.FileField(upload_to='')),
            ],
        ),
    ]
