# Generated by Django 4.2.2 on 2023-12-19 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_admissionform_posted_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlineapplication',
            name='address',
            field=models.CharField(default='Kumasi', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='onlineapplication',
            name='contact',
            field=models.CharField(default='0201234567', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='onlineapplication',
            name='email',
            field=models.EmailField(default='alibernard.learning@gmail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='onlineapplication',
            name='current_academic_report',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
