# Generated by Django 4.2.2 on 2023-12-19 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_article_delete_articles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='texts',
            new_name='quote_1',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='prayer',
            new_name='quote_2',
        ),
    ]
