# Generated by Django 4.2.2 on 2023-12-19 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0044_articlecomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journal',
            old_name='date_posted',
            new_name='created_on',
        ),
        migrations.RenameField(
            model_name='journal',
            old_name='detail_1',
            new_name='paragraph_3',
        ),
        migrations.RenameField(
            model_name='journal',
            old_name='detail_2',
            new_name='paragraph_4',
        ),
        migrations.RenameField(
            model_name='journal',
            old_name='detail_3',
            new_name='paragraph_5',
        ),
        migrations.RenameField(
            model_name='journal',
            old_name='detail_4',
            new_name='paragraph_6',
        ),
        migrations.RenameField(
            model_name='journal',
            old_name='detail_5',
            new_name='paragraph_7',
        ),
        migrations.RenameField(
            model_name='journal',
            old_name='detail_6',
            new_name='paragraph_8',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='author_pic',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='banner',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='blockquote',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='picture_1',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='picture_2',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='picture_3',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='topic_3',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='topic_4',
        ),
        migrations.AddField(
            model_name='journal',
            name='image_1',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='journal',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='journal',
            name='paragraph_1',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='journal',
            name='paragraph_2',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='journal',
            name='paragraph_9',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='journal',
            name='quote_1',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='journal',
            name='quote_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='journal',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='JournalComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=124)),
                ('comment', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.article')),
            ],
        ),
    ]
