# Generated by Django 4.2.2 on 2023-12-19 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_rename_date_posted_journal_created_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalcomment',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.journal'),
        ),
    ]
