# Generated by Django 4.2.2 on 2023-12-19 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_alter_counselor_photo_alter_driver_photo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transportation',
            name='driver_contact',
        ),
        migrations.RemoveField(
            model_name='transportation',
            name='driver_name',
        ),
        migrations.RemoveField(
            model_name='transportation',
            name='driver_picture',
        ),
        migrations.AddField(
            model_name='transportation',
            name='driver',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='core.driver'),
            preserve_default=False,
        ),
    ]
