# Generated by Django 4.2.2 on 2023-12-19 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_remove_transportation_driver_contact_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='')),
                ('received_date', models.DateField()),
            ],
        ),
    ]
