# Generated by Django 4.2.2 on 2023-12-21 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_subject_classes_subject_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='subject_outline_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
