# Generated by Django 4.2.2 on 2023-12-22 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CashCenters',
            new_name='CashCenter',
        ),
    ]
