# Generated by Django 4.2.2 on 2023-12-22 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_incomeexpenditure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomeexpenditure',
            name='receipt_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
