# Generated by Django 4.2.2 on 2023-10-02 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='GPS_Address',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='residence',
            field=models.CharField(default='Kumasi', max_length=100),
            preserve_default=False,
        ),
    ]
