# Generated by Django 4.2.2 on 2023-12-12 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authy', '0002_user_gps_address_user_residence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='registration_fee',
        ),
    ]
