# Generated by Django 4.2.2 on 2023-12-12 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authy', '0003_remove_user_registration_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=100, null=True),
        ),
    ]
