# Generated by Django 4.2.2 on 2023-12-20 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authy', '0005_remove_user_background_img_user_classes_user_cv_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('Student/Parent', 'Student/Parent'), ('Teacher', 'Teacher'), ('Other Staff', 'Other Staff')], default='Student/Parent', max_length=20),
            preserve_default=False,
        ),
    ]
