# Generated by Django 4.2.2 on 2023-12-20 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authy', '0006_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='GPS_Address',
            field=models.CharField(max_length=15),
        ),
    ]
